name: Windows x64 Build

on:
  workflow_call:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: ilammy/setup-nasm@v1.5.1

    - name: Check for Visual Studio 2022 Build Tools and Install if Missing
      run: |
        if (!(Get-Command "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\devenv.exe" -ErrorAction SilentlyContinue)) {
          Write-Host "Visual Studio 2022 Build Tools not found. Installing..."
          choco install visualstudio2022-workload-vctools --yes || throw "Installation failed"
        } else {
          Write-Host "Visual Studio 2022 Build Tools already installed."
        }
      shell: pwsh

    - name: Update Submodules
      working-directory: ${{runner.workspace}}/grpc-labview      
      run: git submodule update --init --recursive

    - name: Create Build Environment
      run: mkdir ${{runner.workspace}}\grpc-labview\build

    - name: Initialize Visual Studio Environment
      run: |
        & "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64

    - name: Configure CMake
      working-directory: ${{runner.workspace}}\grpc-labview\build
      run: cmake -G "Visual Studio 17 2022" -A x64 ..

    - name: Build
      working-directory: ${{runner.workspace}}\grpc-labview\build
      run: cmake --build . --config ${{env.BUILD_TYPE}} -j 16

    - if: ${{ always() }}
      name: Print CMakeTests logs
      run: |
        $directory = "${{runner.workspace}}/grpc-labview/tests/CMakeTests/logs"
        if (Test-Path $directory -PathType Container) {
            Get-ChildItem -Path $directory -File -Recurse | Group-Object Directory | ForEach-Object {
                $subfolderName = $_.Name
                Write-Host "Folder: $subfolderName"
                $_.Group | ForEach-Object {
                    $file = $_
                    Get-Content $file.FullName
                    Write-Host ""
                }
                Write-Host ""
            }
        } else {
            Write-Host "CMakeTests log folder does not exist."
        }

    - name: Tar Build Artifacts
      run: |
        $buildDir = "${{runner.workspace}}\grpc-labview\build\Release"
        if (Test-Path $buildDir) {
            tar -czvf labview-grpc-server-windows-x64.tar.gz -C $buildDir `
            labview_grpc_server.dll `
            labview_grpc_generator.dll
        } else {
            Write-Host "Build directory does not exist. Skipping artifact packaging."
        }

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: labview-grpc-server-windows-x64
        path: labview-grpc-server-windows-x64.tar.gz
        retention-days: 5
